all: locationupdater emailfilter calendarfilter

LocationUpdater: locationupdater.c
	gcc -o locationupdater locationupdater.c
EmailFilter: emailfilter.c
	gcc -o emailfilter emailfilter.c
CalendarFilter: calendarfilter.c
	gcc -o calendarfilter calendarfilter.c
clean: 
	rm -rf locationupdater calendarfilter emailfilter
